---
title: "Data_Prep2"
author: "Dawn Koh"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(stringr)
```

```{r}
# reading the TypeScript file from source: https://github.com/horensen/sg-areas/blob/main/src/data/subzones.ts
ts_file <- readLines("subzones.ts")

# combining lines into one long string
ts_data <- paste(ts_file, collapse = " ")
```

```{r}
# defining regex patterns to extract subzones
pattern_subzone <- "\\[Subzone\\.([A-Z_]+)\\]:"
# extracting and cleaning subzone names
subzone_matches <- str_match_all(ts_data, pattern_subzone)[[1]][, 2]
print(head(subzone_matches))

```


```{r}
# defining regex patterns to extract area names
pattern_name <- 'name:\\s*\\{\\s*en:\\s*"([^"]+)"'
# extracting and cleaning the names
name_matches <- str_match_all(ts_data, pattern_name)[[1]][, 2]
print(head(name_matches))

```

```{r}
# defining regex patterns to extract longitude and latitude coordinate names
pattern_coordinates <- "coordinates: \\{ latitude: (.*?), longitude: (.*?) \\}"
coordinate_matches <- str_extract_all(ts_data, pattern_coordinates)[[1]]

# extracting latitude and longitude values separtely here
# latitudes = 
# longitudes = 

#print(head(latitudes))
#print(head(longitudes))

```


```{r}
# defining regex patterns to extract planning area
pattern_pa <- "area: Area\\.([A-Z_]+),"
# extracting and cleaning area names
pa_matches <- str_match_all(ts_data, pattern_pa)[[1]][, 2]
print(head(pa_matches))
```

```{r}
# create df here with subzone, planning area, latitude, longitude, and name.
# MAKE SURE THE LENGTH OF ALL VARS IS EQUAL AND U CANT JUST TAKE MINIMUM- find out what is gng wrong

# once df looks good use write.csv to write it down- if unsure, dont make this chnage.
```

